### ISSUE TITLE
CoIMS app source

### ISSUE THREAD

**Issue by djanderson** [herlesupreeth/CoIMS_Wiki#6]
Hi Supreeth, 

I have several phones with SIMs provisioned for testing that I don't have physical access to right now. I was thinking instead of trying to collect and reflash the SIMs per this wiki, I might just try and create a Carrier Config app that matches my existing settings and distribute the apk.

Are you planning on open sourcing the code for CoIMS? I see you have other apps released on GitHub, but I didn't see CoIMS. if possible, it would be really useful to see how you did it.

Thanks for the great project,
-Doug

**Comment by herlesupreeth** [comment]
Hello Doug,

I am sorry, i don't intend to publish the source code anytime soon as i am still working on adding new features to it (ability to talk to SIM from app, workaround for hardcoded ePDG address for VoWiFi in UE, etc). (that's why i dont have a proper timeline when i will be able to make it public)

> I was thinking instead of trying to collect and reflash the SIMs per this wiki, I might just try and create a Carrier Config app that matches my existing settings and distribute the apk.

If need be, you can send me the SHA1 certificate you want me to sign the app with and I can try to sign the app with that and send you the apk.

Regards,
Supreeth

**Comment by djanderson** [comment]
Thanks for the info Supreeth, I'll close this issue and keep an eye out for your new features.
